ifndef::imagesdir[:imagesdir: ../../imgs]
ifndef::datatypedir[:datatypedir: ../../examples/src/main/java]
ifndef::datatypetestdir[:datatypetestdir: ../../examples/src/test/java]

[#java-data-types-string]
==== String
*Рядок* - це послідовність символів. Цей клас відзначений ключовим словом `final` тесть є *immutable* об'єктом, який не можна змінити після створення. Операції над `String` об'єктами результатом яких має бути `String` призводять до створення нового об'єкта типу `String`. Будь-який об'єкт Java може бути перетворений на рядок за допомогою методу `toString`, який успадковується всіма об'єктами від класу `Object`.

Починаючи з Java 7 рядки можна використовувати в конструкції `switch`. Використання рядків у switch роблять код читабельніше уникаючи повторення `if-else`. Оператор `switch` використовує `String.equals()` тому необхідно додати перевірку на `null` для уникнення `NullPointerException` так само рядки у чутливі до регістру.

____
*Рядковий літерал* — послідовність символів ув'язнених у подвійні лапки
____

Для маніпуляцій над рядками Java без створення нового рядка є спеціальні класи:

* <<java-data-types-string-StringBuffer, `StringBuffer`>>
* <<java-data-types-string-StringBuilder, `StringBuilder`>>

Об'єкти класу `String` є потокобезпечними через свою незмінність.

При створенні об'єкта String використовуючи подвійні лапки
[source,java]
----
String str1 = "string";
----
віртуальна машина шукає в рядку з таким же значенням і якщо такий рядок є то повертається посилання на існуючий рядок, якщо ні то створюється новий рядок і зберігається в пулі. Якщо ж ми створюємо String за допомогою ключового слова `new`
[source,java]
----
String str = new String("string");
----
у цьому випадку створюється новий об'єкт і поміщається в `heap` але не зберігається в пулі рядків. Для того щоб додати цей рядок в пул можна скористатися методом `intern()` який зробить рядок в пулі або повернуть посилку на існуючу. Але використання рядка через конструктор не дуже хороша практика, так як може призводити до зниження продуктивності, і тільки у разі реальної необхідності мати копію рядка це підхід має місце бути.

[source,java]
----
include::{datatypetestdir}/DataTypeTest.java[tags=dataTypeTest3]
----

Рядки створені  `String s = "s";` додаються в пул __автоматично__.
При використанні `new()`, рядок додається до __heap__ та __НЕ__ додається до string pool.

Клас `String` не дуже хороший вибір, наприклад для роботи з паролями, так як після того, як ви закінчили роботу з паролем він все одно залишається в пулі поки його не видалить збирач сміття. Більш правильний вибір буде використовувати масив для роботи з паролем, оскільки його можна очистити.

Рядки є відмінним варіантом для використання як ключ для `Map`, так як хешкод вираховується один раз при її створенні і не вимагає перерахунку і тому обробляються швидше.

.Порівняння рядків
При використанні оператора `==` ми порівнюємо силкі на об'єкти, тобто якщо дві зменні вказують на один і той самий об'єкт то це порівняння поверне `true`, в іншому випадку поверне `false` навіть якщо навіть тест буде повністю збігатися, тому що цей оператор працює з посиланнями а не порівнює вміст. Для того щоб порівняти вміст треба використати метод `equals()`.

[source,java]
----
include::{datatypetestdir}/DataTypeTest.java[tags=dataTypeTest4]
----

Клас `String` успадковує інтерфейс `Comparable` якій має два методи `compareTo()` та `compareToIgnoreCase(String str)`. Методи порівнюють об'єкти лексикографічно. Якщо поточний рядок передує отриманому рядку, то повертається негативне значення типу `int`, і якщо рядок слідує за отриманим аргументом, то повертає позитивне значення `int`. Якщо метод повернув 0, значить рядок має те саме значення, у цьому випадку і метод 'equals(String str)' так само поверне `true`. Різниця між цими методами що `compareToIgnoreCase(String str)` ігнорує регістр використовуючи `CASE_INSENSITIVE_ORDER` `Comparator`, і якщо метод повертає 0 то і equalsIgnoreCase(String str)` теж поверне `true`

[source,java]
----
include::{datatypetestdir}/DataTypeTest.java[tags=dataTypeTest5]
----

*Конкатенація рядків (+)* — операція об'єднання рядків, спочатку перевіряється наявність такого рідка у пулі рідків якщо існую то повертається силка на існуючий якщо ні то створюється новий об'ект і повертається силка на нього. Як що конкатенація виконуєтсья ні у циклі то компілятор оптімізує таку кокатенацію і тому можна сказати що конкатенація виконуєтсья на етапі компіляції. Якщо у виразі один з операндів є рядком, то результат будь-яких дій буде рядком. Java переводить їх у рядкову виставу за допомогою методу `toString()`. Отримання `NullPointerException` неможливе за допомогою знака конкатенації на відміну від методу `concat`. `concat` теж перевіряє наявність такого рядка у пулі перед створенням нового рідка як що не такого нема.

[source,java]
----
include::{datatypetestdir}/DataTypeTest.java[tags=dataTypeTest6]
----

Навіть якщо зробити ось так:

[source,java]
----
include::{datatypetestdir}/DataTypeTest.java[tags=dataTypeTest11]
----

все одно java створить тільки одну строку тому що значення всіх рядків відомі на етапі компіляції. Але якщо значення рядка не відомо на етапі компіляції а вираховується у рантаймі як показано нижче:

[source,java]
----
include::{datatypetestdir}/DataTypeTest.java[tags=dataTypeTest12]
----

Тобто значення змінної s3 вираховується у рантаймі і не додається у пул.

Для того щоб впевнитися у тому що під час використання `+` та `concat` спочатку перевіряється пул рідків розгляньмо наступний приклад:

[source,java]
----
include::{datatypetestdir}/DataTypeTest.java[tags=dataTypeTest27]
----

Виконавши цей код і перевіривши хешкоди отриманих рядків ми впевнемося що рідкі отримані за допомогою `+` та `concat` мають однокові хешкоди і це означає що вони силаються на одий і той самий об'єкт.

За для зберігання місця застосовуються компактні строки. Доступні значеняя енкодінгу е *LATIN1* *UTF16*. Далеко не для всіх значень необхідно 16 bit. Тому для символів з *LATIN1* виділяється лише 8 bit.

Клас `String` надає можливість створення форматованих рядків. За це відповідає статичний метод `format`. Ось декілька значень які використовуються:

|====
|%s|String
|%d|целое число
|%f|вещественное число
|%b|boolean
|%c|char
|%t|Date
|%%|Символ %
|====

Більш детально можно подивитись https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html#syntax. Але наведемо один приклад:

[source,java]
----
include::{datatypetestdir}/DataTypeTest.java[tags=dataTypeTest13]
----

[#java-data-types-string-StringBuffer]
===== StringBuffer
Так як рядок є не змінним, то для того щоб уникнути створення нових рядків при модифікації існує клас `StringBuffer`. Цей клас може бути використаний в багатопотоковому середовищі так як всі методи цього класу синхронізовані. При створенні `StringBuffer` можна вказати місткість (стандартна становить 16), якщо ж `StringBuffer` створюється з рядка то місткість дорівнюватиме `capacity=str.lenght+16`.

[#java-data-types-string-StringBuilder]
===== StringBuilder
`StringBuilder` - це клас повністю ідентичний `StringBuffer`. Відмінність полягає в тому, що методи цього класу не синхронізовані, відповідно, його не можна використовувати в багатопотокових додатках. Але за рахунок цього він працює швидше.

















// ==== Заголовок
// Для этого нужно будет заглянуть в сам класс, нам интересны все поля, которые не объявлены как static.
//
// [source,java]
// ----
// private final char value[];
// private final int offset;
// private final int count;
// private int hash;
// ----
//
// - Заголовок: 8 байт
// - Поля int: 4 байта * 3 == 12 байт
// - Ссылочная переменная на объект массива: 4 байта
// - Итого: 24 байта
//
// Ну и это еще не все… Так как строка содержит ссылку на массив символов, то, по сути, мы имеем дело с двумя разными объектами — объектом класса String и самим массивом, который хранит строку. Это, как бы, верно с точки зрения ООП, но если посмотреть на это со стороны памяти, то к полученному размеру нужно добавить и размер выделенного для символов массива. А это еще 12 байт на сам объект массива + 2 байта на каждый символ строки. Ну и, конечно же, не забываем добавлять выравнивание для кратности 8 байтам. Итого в конечном итоге простая, казалось бы, строка new String(«a») выливается в:
//
// * new String()
// * Заголовок: 8 байт (для 32-х)
// * Поля int: 4 байта * 3 == 12 байт
// * Ссылочная переменная на объект массива: 4 байта
// * Итого: 24 байта
//
// * new char[1]
// * Заголовок: 8 байт + 4 байта на длину массива == 12 байт
// * Примитивы char: 2 байта * 1 == 2 байта
// * Выравнивание для кратности 8 : 2 байта
// * Итого: 16 байта
//
// *Итого, new String("a") == 40 байт*
// https://topjava.ru/blog/rukovodstvo-po-string-pool-v-java



