ifndef::imagesdir[:imagesdir: ../../imgs]
ifndef::datatypedir[:datatypedir: ../../examples/src/main/java]
ifndef::datatypetestdir[:datatypetestdir: ../../examples/src/test/java]

[#java-data-types-integer]
==== Integer
Розмір змінної типу `int` складає 32 bit та допустимі значення лежать у діапазоні від -2147483648(-2^31) до 2147483647(2^31-1).

Клас `Integer` є класом обгорткою для примітива `int`. Використовується кешування значень з -128 до 127 для значень автоупаковкі.

Також автобоксінг кешує значення від -128 до 127 що зазначено в JLS(5.1.7). Це відбувається тому що вираз `Integer x = 127` = `Integer x = Integer.valueOf(127);`.

[source,java]
----
include::{datatypetestdir}/DataTypeTest.java[tags=dataTypeTest20]
----


////
TODO
.Заголовок
Итак, давайте попробуем подсчитать сколько же будет занимать объект класса Integer в нашей 32-х разрядной HotSpot JVM.
Для этого нужно будет заглянуть в сам класс, нам интересны все поля, которые не объявлены как static. Из таких видим
только одно — int value. Теперь исходя из информации выше получаем:

* Заголовок: 8 байт
* Поле int: 4 байта
* Выравнивание для кратности 8 : 4 байта
* Итого: 16 байт

Для 64-х разрядной:

* Заголовок: 8 байт * 2
* Поле int: 4 байта
* Выравнивание для кратности 8 : 4 байта
* Итого: 24 байт
////
